### PR TITLE
fix: when calibrating dont apply any z offset

### PR DESCRIPTION
**Pull request by krautech**
**Description**

When performing a `CARTOGRAPHER_TOUCH CALIBRATE=1` z offset will no longer be applied prior to calibration. This should fix any weird z_offset stacking issues.

Fixes Issue #51 

Signed-off-by: Chris Krause [krause3284@gmail.com](mailto:krause3284@gmail.com)

### CODE REVIEW

**Review by Jomik — COMMENTED** [review]
Is this actually an issue? I noticed that the `manual_z_offset` is subtracted from the final position at L399.

**Comment by krautech** [comment]
It is, because its applying the `manual_z_offset` before calibration where calibration should have 0 offset.

I added L387-388 to counter it.

**Comment by Jomik** [comment]
> It is, because its applying the `manual_z_offset` before calibration where calibration should have 0 offset.
> 
> I added L387-388 to counter it.

Oh I see now.. The offset is applied here in the touch https://github.com/Cartographer3D/cartographer-klipper/blob/6d7af6e7ea6dab54e23ce6f1c1251da41ff7e63c/scanner.py#L500
But then again here https://github.com/Cartographer3D/cartographer-klipper/blob/6d7af6e7ea6dab54e23ce6f1c1251da41ff7e63c/scanner.py#L399
Should that line be removed actually? Line 399. That makes no sense to me 🤔

And I get now why offset should be 0 👍

**Review by Jomik — APPROVED** [review]

**Comment by krautech** [comment]
Ahhh I see what you mean, it's not doing anything, it's just redundant. I
think removing 399 makes sense 👍🏼

**Review by Jomik — APPROVED** [review]

**Pull request merged**
